apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: yussufzoulfakar/chatingapp:1.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: "chatdb"
        - name: MONGO_HOST
          value: 192.168.118.200
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app
spec:
  selector:
    app: chat-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
