name: Terraform Infra & K8s Apply

on:
  workflow_run:
    workflows: ["EKS_Deploy"]
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > my-ec2-key.pem
          chmod 600 my-ec2-key.pem

      - name: Add key to SSH agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add my-ec2-key.pem


      - name: Test raw SSH through bastion
        run: |
          ssh -o "StrictHostKeyChecking=no" \
              -o ProxyCommand="ssh -i my-ec2-key.pem -W %h:%p ec2-user@3.232.133.47" \
              -i my-ec2-key.pem ec2-user@192.168.82.19 "hostname"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/mongodb-playbook.yml --private-key my-ec2-key.pem