name: Terraform Infra & K8s Apply

on:
  workflow_run:
    workflows: ["EKS_Deploy"]
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Decode Bastion and EC2 Keys
        run: |
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > bastion.pem
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > my-ec2-key.pem
          chmod 600 bastion.pem my-ec2-key.pem

      - name: Add both keys to SSH agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add bastion.pem
          ssh-add my-ec2-key.pem

      - name: Run Ansible Playbook
        working-directory: ansible/ansible
        run: |
          ansible-playbook -i inventory mongodb-playbook.yml --private-key my-ec2-key.pem
